[package]
name = "mariposa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smt2parser = {path="smt2utils/smt2parser"}
rand = "0.8.5"
rustop = "1.1.2"
rand_chacha = "0.3.1"